openapi: 3.0.1
info:
  title: WSO2 Identity Server OAuth2 Dynamic Client Registration Endpoint
  description: |
    This document specifies an OAuth2 Dyanmic Client Registration Endpoint for WSO2 Identity Server.
  contact:
    name: WSO2
    url: http://wso2.com/identity-and-access-management
    email: architecture@wso2.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.1.0
servers:
- url: https:/{serverUrl}/api/identity/oauth2/dcr/v1.1
  variables:
    serverUrl:
      default: localhost:9443
security:
- OAuth2: []
- BasicAuth: []
paths:
  /register:
    get:
      tags:
      - OAuth2 DCR
      summary: |
        Get OAuth2 application information
      description: |
        This API is used to get/retrieve an OAuth2 application by client_name.
      operationId: getApplicationByName
      parameters:
      - name: client_name
        in: query
        description: Unique identifier of the OAuth2 client application.
        required: true
        schema:
          type: string
      responses:
        200:
          description: Successfully Retrieved
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/application'
        401:
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
        500:
          description: Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
      x-wso2-request: |
        curl -X GET -H "Authorization: Basic YWRtaW46YWRtaW4=" -H "Content-Type: application/json" -d '{}' "https://localhost:9443/api/identity/oauth2/dcr/v1.1/register?client_name=application_owner_application_1"
      x-wso2-response: |
        "HTTP/1.1 200 OK"
        { "client_id": "s6BhdRkqt3",
        "client_secret":"ZJYCqe3GGRvdrudKyZS0XhGv_Z45DuKhCUk0gBR1vZk",
        "client_secret_expires_at": 1577858400,
        "redirect_uris":["https://client.example.org/callback"],
        "client_name":"application_owner_application_1",
        "grant_types": ["password"]}
    post:
      tags:
      - OAuth2 DCR
      summary: |
        Registers an OAuth2 application
      description: "This API is used to create an OAuth2 application. If your want\
        \ to create your application to use the implicit or authorization_code \n\
        grant types, you need to provide the redirect_uris field in your request.\
        \ If you are using any other grant type, \nsuch as password, you don't need\
        \ to send the redirect_uri field in the request. Check the sample request\
        \ given below.\n"
      operationId: registerApplication
      requestBody:
        description: Application information to register.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/registrationRequest'
        required: true
      responses:
        201:
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/application'
        400:
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
        409:
          description: Conflict
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
        500:
          description: Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
      x-wso2-request: |
        curl -X POST -H "Authorization: Basic YWRtaW46YWRtaW4=" -H
        "Content-Type: application/json" -d '{
          "redirect_uris":[""],
          "client_name": "application_1",
          "grant_types": ["password"] }'
        "https://localhost:9443/api/identity/oauth2/dcr/v1.1/register"
      x-wso2-response: |
        "HTTP/1.1 201 Created"
        { "client_id": "s6BhdRkqt3",
        "client_secret":"ZJYCqe3GGRvdrudKyZS0XhGv_Z45DuKhCUk0gBR1vZk",
        "client_secret_expires_at": 1577858400,
        "redirect_uris":[""],
        "grant_types": ["password"],
        "client_name":"application_1" }
      x-codegen-request-body-name: registrationRequest
  /register/{client_id}:
    get:
      tags:
      - OAuth2 DCR
      summary: |
        Get OAuth2 application information
      description: |
        This API is used to get/retrieve an OAuth2 application by client_id.
      operationId: getApplication
      parameters:
      - name: client_id
        in: path
        description: Unique identifier of the OAuth2 client application.
        required: true
        schema:
          type: string
      responses:
        200:
          description: Successfully Retrieved
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/application'
        404:
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
        500:
          description: Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
      x-wso2-request: |
        curl -X GET -H "Authorization: Basic YWRtaW46YWRtaW4=" -H "Content-Type: application/json" -d '{}' "https://localhost:9443/api/identity/oauth2/dcr/v1.1/register/s6BhdRkqt3"
      x-wso2-response: |
        "HTTP/1.1 200 OK"
        { "client_id": "s6BhdRkqt3",
        "client_secret":"ZJYCqe3GGRvdrudKyZS0XhGv_Z45DuKhCUk0gBR1vZk",
        "client_secret_expires_at": 1577858400,
        "redirect_uris":["https://client.example.org/callback"],
        "grant_types": ["password"],
        "client_name":"application_owner_application_1" }
    put:
      tags:
      - OAuth2 DCR
      summary: |
        Updates an OAuth2 application
      description: |
        This API is used to update an OAuth2 application.
      operationId: updateApplication
      parameters:
      - name: client_id
        in: path
        description: Unique identifier for the OAuth2 client application.
        required: true
        schema:
          type: string
      requestBody:
        description: Application information to update.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/updateRequest'
        required: true
      responses:
        200:
          description: Successfully updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/application'
        400:
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
        409:
          description: Conflict
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
        500:
          description: Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
      x-wso2-request: |
        curl -X PUT -H "Authorization: Basic YWRtaW46YWRtaW4=" -H
        "Content-Type: application/json" -d '{
          "redirect_uris":["https://client.example.org/callback"],
          "client_name": "application_1",
          "grant_types": ["password"] }'
        "https://localhost:9443/api/identity/oauth2/dcr/v1.1/register"
      x-wso2-response: |
        "HTTP/1.1 200 OK"
        { "client_id": "s6BhdRkqt3",
        "client_secret":"ZJYCqe3GGRvdrudKyZS0XhGv_Z45DuKhCUk0gBR1vZk",
        "client_secret_expires_at": 1577858400,
        "redirect_uris":["https://client.example.org/callback"],
        "grant_types": ["password"],
        "client_name":"application_owner_application_1" }
      x-codegen-request-body-name: updateRequest
    delete:
      tags:
      - OAuth2 DCR
      summary: |
        Delete OAuth2 application
      description: |
        This API is used to delete an OAuth2 application by client_id.
      operationId: deleteApplication
      parameters:
      - name: client_id
        in: path
        description: Unique identifier of the OAuth2 client application.
        required: true
        schema:
          type: string
      responses:
        204:
          description: Successfully deleted
          content: {}
        404:
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
        500:
          description: Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
      x-wso2-request: |
        curl -X DELETE -H "Authorization: Basic YWRtaW46YWRtaW4=" -H "Content-Type: application/json" -d '{}' "https://localhost:9443/api/identity/oauth2/dcr/v1.1/register/s6BhdRkqt3"
      x-wso2-response: |
        "HTTP/1.1 204 No Content"
components:
  schemas:
    registrationRequest:
      type: object
      required:
        - redirect_uris
        - client_name
      properties:
        redirect_uris:
          type: array
          items:
            type: string
          description: "Array of redirection URIs for the application. These URIs are used as redirect targets after successful authentication."
        client_name:
          type: string
          description: "The name of the client application."
        client_id:
          type: string
          description: "The client identifier issued to the client during the registration process."
        client_secret:
          type: string
          description: "The client secret issued to the client during the registration process."
        grant_types:
          type: array
          items:
            type: string
          description: "Array of OAuth 2.0 grant types that the client can use."
        application_type:
          type: string
          description: "Type of the application. Can be either 'web' or 'native'."
        jwks_uri:
          type: string
          description: "URL for the client's JSON Web Key Set document."
        url:
          type: string
          description: "URL of the client application."
        ext_param_client_id:
          type: string
          description: "External parameter for the client ID."
        ext_param_client_secret:
          type: string
          description: "External parameter for the client secret."
        contacts:
          type: array
          items:
            type: string
          description: "Array of client contact information."
        post_logout_redirect_uris:
          type: array
          items:
            type: string
          description: "Array of URLs to which the client will be redirected after logout."
        request_uris:
          type: array
          items:
            type: string
          description: "Array of URLs that are allowed to make requests."
        response_types:
          type: array
          items:
            type: string
          description: "Array of OAuth 2.0 response types that the client can use."
        ext_param_sp_template:
          type: string
          description: "External parameter for the service provider template."
        backchannel_logout_uri:
          type: string
          description: "URI for the client's back-channel logout mechanism."
        backchannel_logout_session_required:
          type: boolean
          description: "Specifies whether a logout session is required for back-channel logout."
        ext_application_display_name:
          type: string
          description: "This parameter is used to set a display name for the application."
        token_type_extension:
          type: string
          description: "The token type extension."
        ext_application_owner:
          type: string
          description: "This parameter is used for specifying the owner of the application."
        ext_application_token_lifetime:
          type: integer
          format: int64
          description: "This parameter is used for specifying the lifetime of the application token."
        ext_user_token_lifetime:
          type: integer
          format: int64
          description: "This parameter is used for specifying the lifetime of the user token."
        ext_refresh_token_lifetime:
          type: integer
          format: int64
          description: "This parameter is used for specifying the lifetime of the refresh token."
        ext_id_token_lifetime:
          type: integer
          format: int64
          description: "This parameter is used for specifying the lifetime of the ID token."
        ext_pkce_mandatory:
          type: boolean
          description: "This parameter is used for specifying whether the Proof Key for Code Exchange (PKCE) is mandatory."
        ext_pkce_support_plain:
          type: boolean
          description: "This parameter is used for specifying whether the PKCE supports 'plain' challenge method."
        ext_public_client:
          type: boolean
          description: "This parameter is used for specifying whether the client is a public client."
    updateRequest:
      type: object
      properties:
        redirect_uris:
          type: array
          items:
            type: string
          description: "Array of redirection URIs for the application. These URIs are used as redirect targets after successful authentication."
        client_name:
          type: string
          description: "The updated name of the client application."
        client_id:
          type: string
          description: "The client identifier issued to the client during the registration process. It should be the same as the one in the original registration request."
        client_secret:
          type: string
          description: "The client secret issued to the client during the registration process. It should be the same as the one in the original registration request."
        grant_types:
          type: array
          items:
            type: string
          description: "Array of OAuth 2.0 grant types that the client is updated to use."
        backchannel_logout_uri:
          type: string
          description: "Updated URI for the client's back-channel logout mechanism."
        backchannel_logout_session_required:
          type: boolean
          description: "Updated requirement for whether a logout session is required for back-channel logout."
        ext_application_display_name:
          type: string
          description: "This parameter is used to update the display name for the application."
        token_type_extension:
          type: string
          description: "The updated token type extension."
        ext_application_owner:
          type: string
          description: "This parameter is used for updating the owner of the application."
        ext_application_token_lifetime:
          type: integer
          format: int64
          description: "This parameter is used for updating the lifetime of the application token."
        ext_user_token_lifetime:
          type: integer
          format: int64
          description: "This parameter is used for updating the lifetime of the user token."
        ext_refresh_token_lifetime:
          type: integer
          format: int64
          description: "This parameter is used for updating the lifetime of the refresh token."
        ext_id_token_lifetime:
          type: integer
          format: int64
          description: "This parameter is used for updating the lifetime of the ID token."
        ext_pkce_mandatory:
          type: boolean
          description: "This parameter is used for specifying whether the Proof Key for Code Exchange (PKCE) is mandatory."
        ext_pkce_support_plain:
          type: boolean
          description: "This parameter is used for specifying whether the PKCE supports 'plain' challenge method."
        ext_public_client:
          type: boolean
          description: "This parameter is used for specifying whether the client is a public client."
    application:
      type: object
      properties:
        client_id:
          type: string
        client_secret:
          type: string
        client_secret_expires_at:
          type: string
        redirect_uris:
          type: array
          items:
            type: string
        grant_types:
          type: array
          items:
            type: string
        client_name:
          type: string
    error:
      type: object
      properties:
        error:
          type: string
        error_description:
          type: string
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
    OAuth2:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: https://localhost:9443/oauth2/authorize
          tokenUrl: https://localhost:9443/oauth2/token
          scopes: {}
